// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analizadores/Lexico.jflex

package analizadores;
import java_cup.runtime.Symbol;


@SuppressWarnings("fallthrough")
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMENTARIO = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\u10fe\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\2\22\0\1\1\1\3"+
    "\1\4\1\5\2\0\1\6\1\0\1\7\1\10\1\11"+
    "\1\0\1\12\1\0\1\13\1\0\12\14\1\15\1\16"+
    "\1\17\1\20\1\21\2\0\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\31\1\34"+
    "\1\31\1\35\1\36\1\37\1\31\1\40\1\41\1\42"+
    "\1\43\2\31\1\44\1\45\1\31\1\46\1\0\1\47"+
    "\1\0\1\31\1\0\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\31\1\34\1\31"+
    "\1\35\1\36\1\37\1\31\1\40\1\41\1\42\1\43"+
    "\2\31\1\44\1\45\1\31\1\50\1\51\1\52\262\0"+
    "\2\53\115\0\1\54\u0180\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\3\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\16\17\1\20\1\21\1\22\1\1\1\23\2\1\2\24"+
    "\1\25\1\0\1\26\1\27\1\30\1\31\1\0\1\32"+
    "\1\33\1\34\2\17\1\35\7\17\1\0\12\17\1\0"+
    "\1\36\3\0\1\37\1\40\1\41\11\17\2\0\1\42"+
    "\3\17\1\43\5\17\2\44\1\42\1\43\2\0\1\17"+
    "\1\45\4\17\1\0\3\17\2\0\1\46\1\17\1\47"+
    "\2\17\1\0\1\17\1\50\1\17\1\0\1\51\1\52"+
    "\2\17\2\53\2\17\1\54\2\0\1\17\1\55\1\17"+
    "\1\0\1\56\1\17\1\55\1\17\1\57\2\60\2\61"+
    "\1\62\2\63\1\64\1\17\1\0\2\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\132\0\132\0\132\0\132\0\132\0\u0168\0\132\0\132"+
    "\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3\0\u02d0"+
    "\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de\0\u040b\0\u0438"+
    "\0\u0465\0\132\0\132\0\132\0\u0492\0\132\0\u04bf\0\u04ec"+
    "\0\132\0\u0519\0\132\0\341\0\132\0\u0546\0\132\0\132"+
    "\0\u0573\0\132\0\132\0\132\0\u05a0\0\u05cd\0\u032a\0\u05fa"+
    "\0\u0627\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762"+
    "\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca"+
    "\0\u08f7\0\u0924\0\132\0\u0951\0\u097e\0\u09ab\0\132\0\u0573"+
    "\0\u032a\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6"+
    "\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u032a\0\u0bc7\0\u0bf4\0\u0c21"+
    "\0\u032a\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02\0\u032a\0\132"+
    "\0\132\0\132\0\u0d2f\0\u0d5c\0\u0d89\0\u032a\0\u0db6\0\u0de3"+
    "\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4\0\u0ef1\0\u0f1e\0\u0f4b"+
    "\0\u032a\0\u0f78\0\u032a\0\u0fa5\0\u0fd2\0\u0fff\0\u102c\0\u032a"+
    "\0\u1059\0\u1086\0\u032a\0\u032a\0\u10b3\0\u10e0\0\u032a\0\132"+
    "\0\u110d\0\u113a\0\u032a\0\u1167\0\u1194\0\u11c1\0\u032a\0\u11ee"+
    "\0\u121b\0\u032a\0\u1248\0\132\0\u1275\0\u032a\0\u032a\0\132"+
    "\0\u032a\0\132\0\u032a\0\u032a\0\132\0\u032a\0\u12a2\0\u12cf"+
    "\0\u032a\0\132";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\2\32"+
    "\1\33\2\32\1\34\1\35\1\32\1\36\1\37\1\40"+
    "\1\41\2\32\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\5\51\1\52\47\51\56\0\2\4\72\0\1\53"+
    "\34\0\4\54\1\55\50\54\5\0\1\56\3\0\1\57"+
    "\51\0\1\60\61\0\1\61\1\16\60\0\1\62\54\0"+
    "\1\63\54\0\1\64\50\0\1\32\5\0\3\32\1\65"+
    "\12\32\1\66\1\32\1\67\3\32\23\0\1\32\5\0"+
    "\14\32\1\70\7\32\23\0\1\32\5\0\12\32\1\71"+
    "\11\32\23\0\1\32\5\0\1\72\23\32\23\0\1\32"+
    "\5\0\22\32\1\73\1\32\23\0\1\32\5\0\1\74"+
    "\7\32\1\75\1\32\1\76\11\32\5\0\1\77\15\0"+
    "\1\32\5\0\24\32\23\0\1\32\5\0\13\32\1\100"+
    "\10\32\23\0\1\32\5\0\21\32\1\101\2\32\23\0"+
    "\1\32\5\0\1\32\1\102\22\32\23\0\1\32\5\0"+
    "\4\32\1\103\17\32\23\0\1\32\5\0\4\32\1\104"+
    "\13\32\1\105\3\32\23\0\1\32\5\0\1\106\15\32"+
    "\1\107\5\32\23\0\1\32\5\0\15\32\1\110\1\32"+
    "\1\111\4\32\6\0\1\112\51\0\1\113\40\0\1\114"+
    "\45\0\1\115\13\0\1\116\23\0\1\117\43\0\2\56"+
    "\1\0\52\56\14\0\1\120\54\0\1\32\5\0\3\32"+
    "\1\121\20\32\23\0\1\32\5\0\16\32\1\122\5\32"+
    "\23\0\1\32\5\0\14\32\1\123\7\32\23\0\1\32"+
    "\5\0\4\32\1\124\17\32\23\0\1\32\5\0\20\32"+
    "\1\125\3\32\23\0\1\32\5\0\15\32\1\126\6\32"+
    "\23\0\1\32\5\0\12\32\1\127\11\32\23\0\1\32"+
    "\5\0\4\32\1\130\5\32\1\131\11\32\23\0\1\32"+
    "\5\0\14\32\1\132\7\32\35\0\1\133\5\0\1\134"+
    "\34\0\1\32\5\0\20\32\1\135\3\32\23\0\1\32"+
    "\5\0\12\32\1\136\11\32\23\0\1\32\5\0\11\32"+
    "\1\137\12\32\23\0\1\32\5\0\1\140\23\32\23\0"+
    "\1\32\5\0\20\32\1\141\3\32\23\0\1\32\5\0"+
    "\14\32\1\142\1\32\1\143\5\32\23\0\1\32\5\0"+
    "\1\32\1\144\22\32\23\0\1\32\5\0\21\32\1\145"+
    "\2\32\23\0\1\32\5\0\3\32\1\146\20\32\23\0"+
    "\1\32\5\0\4\32\1\147\17\32\35\0\1\150\70\0"+
    "\1\151\54\0\1\152\50\0\1\153\1\0\1\154\30\0"+
    "\1\32\5\0\1\155\23\32\23\0\1\32\5\0\12\32"+
    "\1\156\11\32\23\0\1\32\5\0\1\157\23\32\23\0"+
    "\1\32\5\0\1\160\23\32\23\0\1\32\5\0\14\32"+
    "\1\161\7\32\23\0\1\32\5\0\17\32\1\162\4\32"+
    "\6\0\1\163\14\0\1\32\5\0\12\32\1\164\11\32"+
    "\23\0\1\32\5\0\20\32\1\165\3\32\23\0\1\32"+
    "\5\0\1\166\23\32\43\0\1\167\62\0\1\170\26\0"+
    "\1\32\5\0\12\32\1\171\11\32\23\0\1\32\5\0"+
    "\4\32\1\172\17\32\23\0\1\32\5\0\3\32\1\173"+
    "\20\32\23\0\1\32\5\0\16\32\1\174\5\32\23\0"+
    "\1\32\5\0\10\32\1\175\13\32\5\0\1\176\15\0"+
    "\1\32\5\0\12\32\1\177\11\32\23\0\1\32\5\0"+
    "\4\32\1\200\17\32\23\0\1\32\5\0\1\201\23\32"+
    "\47\0\1\202\46\0\1\176\20\0\1\176\15\0\1\32"+
    "\5\0\23\32\1\203\23\0\1\32\5\0\16\32\1\204"+
    "\5\32\23\0\1\32\5\0\1\32\1\205\22\32\23\0"+
    "\1\32\5\0\16\32\1\206\5\32\23\0\1\32\5\0"+
    "\4\32\1\207\17\32\35\0\1\210\42\0\1\32\5\0"+
    "\3\32\1\211\20\32\23\0\1\32\5\0\4\32\1\212"+
    "\17\32\23\0\1\32\5\0\20\32\1\213\3\32\34\0"+
    "\1\214\55\0\1\215\42\0\1\32\5\0\2\32\1\216"+
    "\21\32\23\0\1\32\5\0\4\32\1\217\17\32\23\0"+
    "\1\32\5\0\13\32\1\220\10\32\44\0\1\221\33\0"+
    "\1\32\5\0\4\32\1\222\17\32\23\0\1\32\5\0"+
    "\20\32\1\223\3\32\35\0\1\224\42\0\1\32\5\0"+
    "\1\225\23\32\23\0\1\32\5\0\20\32\1\226\3\32"+
    "\23\0\1\32\5\0\17\32\1\227\4\32\6\0\1\230"+
    "\14\0\1\32\5\0\16\32\1\231\5\32\50\0\1\230"+
    "\12\0\1\230\40\0\1\232\30\0\1\32\5\0\20\32"+
    "\1\233\3\32\23\0\1\32\5\0\6\32\1\234\15\32"+
    "\37\0\1\235\40\0\1\32\5\0\4\32\1\236\17\32"+
    "\23\0\1\32\5\0\17\32\1\237\4\32\6\0\1\240"+
    "\14\0\1\32\5\0\4\32\1\241\17\32\35\0\1\242"+
    "\26\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4860];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\5\1\5\11\1\1\2\11\21\1\3\11"+
    "\1\1\1\11\2\1\1\11\1\1\1\11\1\0\1\11"+
    "\1\1\2\11\1\0\3\11\12\1\1\0\12\1\1\0"+
    "\1\11\3\0\1\11\13\1\2\0\13\1\3\11\2\0"+
    "\6\1\1\0\3\1\2\0\5\1\1\0\3\1\1\0"+
    "\5\1\1\11\3\1\2\0\3\1\1\0\2\1\1\11"+
    "\3\1\1\11\1\1\1\11\2\1\1\11\2\1\1\0"+
    "\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }
    
    private Symbol symbol(int type) {
        return new Symbol(type, yyline+1, yycolumn+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { entorno.Contexto.getInstancia().agregarError("Lexico", "Simbolo no reconocido: " + yytext(), yyline+1, yycolumn+1);
    System.err.println("Error lexico: " + yytext());
            }
          // fall through
          case 54: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 55: break;
          case 3:
            { return symbol(sym.NOT);
            }
          // fall through
          case 56: break;
          case 4:
            { return symbol(sym.PAR_A);
            }
          // fall through
          case 57: break;
          case 5:
            { return symbol(sym.PAR_C);
            }
          // fall through
          case 58: break;
          case 6:
            { return symbol(sym.ASTERISCO);
            }
          // fall through
          case 59: break;
          case 7:
            { return symbol(sym.COMA);
            }
          // fall through
          case 60: break;
          case 8:
            { return symbol(sym.PUNTO);
            }
          // fall through
          case 61: break;
          case 9:
            { return symbol(sym.ENTERO, yytext());
            }
          // fall through
          case 62: break;
          case 10:
            { return symbol(sym.DOSPUNTOS);
            }
          // fall through
          case 63: break;
          case 11:
            { return symbol(sym.PUNTOCOMA);
            }
          // fall through
          case 64: break;
          case 12:
            { return symbol(sym.MENOR);
            }
          // fall through
          case 65: break;
          case 13:
            { return symbol(sym.IGUAL);
            }
          // fall through
          case 66: break;
          case 14:
            { return symbol(sym.MAYOR);
            }
          // fall through
          case 67: break;
          case 15:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 68: break;
          case 16:
            { return symbol(sym.COR_A);
            }
          // fall through
          case 69: break;
          case 17:
            { return symbol(sym.COR_C);
            }
          // fall through
          case 70: break;
          case 18:
            { return symbol(sym.LLAVE_A);
            }
          // fall through
          case 71: break;
          case 19:
            { return symbol(sym.LLAVE_C);
            }
          // fall through
          case 72: break;
          case 20:
            { /* Ignorar todo dentro del comentario */
            }
          // fall through
          case 73: break;
          case 21:
            { return symbol(sym.DIFERENTE);
            }
          // fall through
          case 74: break;
          case 22:
            { return symbol(sym.CADENA, yytext());
            }
          // fall through
          case 75: break;
          case 23:
            { /* Ignorar comentario de linea */
            }
          // fall through
          case 76: break;
          case 24:
            { yybegin(COMENTARIO);
            }
          // fall through
          case 77: break;
          case 25:
            { return symbol(sym.AND);
            }
          // fall through
          case 78: break;
          case 26:
            { return symbol(sym.MENOR_IGUAL);
            }
          // fall through
          case 79: break;
          case 27:
            { return symbol(sym.IGUAL_IGUAL);
            }
          // fall through
          case 80: break;
          case 28:
            { return symbol(sym.MAYOR_IGUAL);
            }
          // fall through
          case 81: break;
          case 29:
            { return symbol(sym.PR_AT, yytext());
            }
          // fall through
          case 82: break;
          case 30:
            { return symbol(sym.OR);
            }
          // fall through
          case 83: break;
          case 31:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 84: break;
          case 32:
            { return symbol(sym.DECIMAL, yytext());
            }
          // fall through
          case 85: break;
          case 33:
            { return symbol(sym.PR_ADD, yytext());
            }
          // fall through
          case 86: break;
          case 34:
            { return symbol(sym.TIP_INT, yytext());
            }
          // fall through
          case 87: break;
          case 35:
            { return symbol(sym.PR_SET, yytext());
            }
          // fall through
          case 88: break;
          case 36:
            { return symbol(sym.PR_USE, yytext());
            }
          // fall through
          case 89: break;
          case 37:
            { return symbol(sym.TIP_BOOL, yytext());
            }
          // fall through
          case 90: break;
          case 38:
            { return symbol(sym.NULL);
            }
          // fall through
          case 91: break;
          case 39:
            { return symbol(sym.PR_READ, yytext());
            }
          // fall through
          case 92: break;
          case 40:
            { return symbol(sym.TRUE);
            }
          // fall through
          case 93: break;
          case 41:
            { return symbol(sym.TIP_ARRAY, yytext());
            }
          // fall through
          case 94: break;
          case 42:
            { return symbol(sym.PR_CLEAR, yytext());
            }
          // fall through
          case 95: break;
          case 43:
            { return symbol(sym.FALSE);
            }
          // fall through
          case 96: break;
          case 44:
            { return symbol(sym.TIP_FLOAT, yytext());
            }
          // fall through
          case 97: break;
          case 45:
            { return symbol(sym.PR_STORE, yytext());
            }
          // fall through
          case 98: break;
          case 46:
            { return symbol(sym.PR_TABLE, yytext());
            }
          // fall through
          case 99: break;
          case 47:
            { return symbol(sym.PR_EXPORT, yytext());
            }
          // fall through
          case 100: break;
          case 48:
            { return symbol(sym.PR_FIELDS, yytext());
            }
          // fall through
          case 101: break;
          case 49:
            { return symbol(sym.PR_FILTER, yytext());
            }
          // fall through
          case 102: break;
          case 50:
            { return symbol(sym.TIP_OBJECT, yytext());
            }
          // fall through
          case 103: break;
          case 51:
            { return symbol(sym.TIP_STRING, yytext());
            }
          // fall through
          case 104: break;
          case 52:
            { return symbol(sym.PR_UPDATE, yytext());
            }
          // fall through
          case 105: break;
          case 53:
            { return symbol(sym.PR_DATABASE, yytext());
            }
          // fall through
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
