
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PR_TABLE = 4;
  public static final int DOSPUNTOS = 29;
  public static final int ENTERO = 45;
  public static final int DIFERENTE = 34;
  public static final int TIP_INT = 15;
  public static final int PR_USE = 3;
  public static final int PUNTOCOMA = 28;
  public static final int LLAVE_C = 22;
  public static final int ASTERISCO = 31;
  public static final int PR_DATABASE = 2;
  public static final int LLAVE_A = 21;
  public static final int PR_READ = 5;
  public static final int NOT = 41;
  public static final int AND = 39;
  public static final int PR_CLEAR = 14;
  public static final int PR_EXPORT = 10;
  public static final int IGUAL = 32;
  public static final int PR_FIELDS = 6;
  public static final int OR = 40;
  public static final int TIP_OBJECT = 20;
  public static final int TIP_BOOL = 18;
  public static final int PR_ADD = 11;
  public static final int ID = 48;
  public static final int IGUAL_IGUAL = 33;
  public static final int DECIMAL = 46;
  public static final int EOF = 0;
  public static final int TIP_FLOAT = 17;
  public static final int TRUE = 42;
  public static final int error = 1;
  public static final int COMA = 27;
  public static final int CADENA = 47;
  public static final int NULL = 44;
  public static final int MENOR = 35;
  public static final int PAR_C = 24;
  public static final int PAR_A = 23;
  public static final int PR_STORE = 8;
  public static final int MAYOR = 36;
  public static final int PR_AT = 9;
  public static final int PUNTO = 30;
  public static final int MAYOR_IGUAL = 38;
  public static final int PR_SET = 13;
  public static final int COR_C = 26;
  public static final int MENOR_IGUAL = 37;
  public static final int TIP_STRING = 16;
  public static final int FALSE = 43;
  public static final int COR_A = 25;
  public static final int TIP_ARRAY = 19;
  public static final int PR_UPDATE = 12;
  public static final int PR_FILTER = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_DATABASE",
  "PR_USE",
  "PR_TABLE",
  "PR_READ",
  "PR_FIELDS",
  "PR_FILTER",
  "PR_STORE",
  "PR_AT",
  "PR_EXPORT",
  "PR_ADD",
  "PR_UPDATE",
  "PR_SET",
  "PR_CLEAR",
  "TIP_INT",
  "TIP_STRING",
  "TIP_FLOAT",
  "TIP_BOOL",
  "TIP_ARRAY",
  "TIP_OBJECT",
  "LLAVE_A",
  "LLAVE_C",
  "PAR_A",
  "PAR_C",
  "COR_A",
  "COR_C",
  "COMA",
  "PUNTOCOMA",
  "DOSPUNTOS",
  "PUNTO",
  "ASTERISCO",
  "IGUAL",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "NULL",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ID"
  };
}

